name: Main
on:
  push:
    branches: [release]
  pull_request:
    types: [opened, synchronize]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate lockfile
        run: bundle lock

      - name: Bundle
        run: bundle check || bundle install

      - name: Run tests
        run: bundle exec rake test
